#!/usr/bin/env python3
'''
Author: Cosmade
Date: 2024-04-09 10:47:48
LastEditors: deepskystar deepskystar@outlook.com
LastEditTime: 2024-04-09 15:39:21
FilePath: /hikit/hi
Description: 

Copyright 2024 Cosmade

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an 
'''
from hikit import *

if __name__ == "__main__":
    main()
    pass
