#!/bin/bash
# -*- coding: utf-8 -*-s
###
 # @Author: Cosmade
 # @Date: 2024-04-09 15:55:33
 # @LastEditors: deepskystar deepskystar@outlook.com
 # @LastEditTime: 2024-05-23 17:44:36
 # @FilePath: /hikit/setup
 # @Description: 
 # 
 # Copyright 2024 Cosmade
 # 
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 # http://www.apache.org/licenses/LICENSE-2.0
 # 
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
### 

rm -r -f ~/.hikit
# check -d is install directly
if [ "$1" == "-d" ]; then
    echo "Install to python enviroment directly..."
    python3 -m pip install --user -r requirements.txt
else
    mkdir ~/.hikit
    python3 -m venv ~/.hikit/hienv
    source ~/.hikit/hienv/bin/activate
    python3 -m pip install -r requirements.txt
fi


python3 hi_basic_setup.py
python3 hi_setup.py

# check -d is install directly
if [ "$1" == "-d" ]; then
    echo "Finished install to python enviroment directly."
else
    deactivate
fi

if [ -e "~/.bashrc" ]; then
    source ~/.bashrc
fi

if [ -e "~/.zshrc" ]; then
    source ~/.zshrc
fi

