#!/bin/bash
# -*- coding: utf-8 -*-s
###
 # @Author: Cosmade
 # @Date: 2024-04-09 15:55:33
 # @LastEditors: deepskystar deepskystar@outlook.com
 # @LastEditTime: 2024-05-15 20:59:30
 # @FilePath: /hikit/setup
 # @Description: 
 # 
 # Copyright 2024 Cosmade
 # 
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 # http://www.apache.org/licenses/LICENSE-2.0
 # 
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
### 

rm -r -f ~/.hikit
python3 -m pip install --user -r requirements.txt
python3 hi_basic_setup.py
python3 hi_setup.py

if [ -e "~/.bashrc" ]; then
    source ~/.bashrc
fi

if [ -e "~/.zshrc" ]; then
    source ~/.zshrc
fi
